TheHive-Project/TheHive4py

- setup.py
Hey guys, 
I noticed that installing `thehive4py` from PyPI doesn't let you use the client, because `python-magic` package is missing in the `setup.py`. The error message I receive is:
```
...
from thehive4py.api import TheHiveApi
File "/home/ilya/thehive-env/lib/python3.5/site-packages/thehive4py/api.py", line 8, in <module>
import magic
ImportError: No module named 'magic'
```
Same for python 2.7:
```
...
from thehive4py.api import TheHiveApi
File "/home/ilya/.local/share/virtualenvs/thehive-LPUGdsMD/local/lib/python2.7/site-packages/thehive4py/api.py", line 8, in <module>
import magic
ImportError: No module named magic
```
This PR should resolve the issue.
> Install python-magic package on setup

- thehive4py/models.py
The default severity is mentioned to default `2` in the [official API documentation](https://github.com/CERT-BDF/TheHiveDocs/blob/master/api/alert.md#model-definition), not `3`.
This also makes it consistent with the default value for a case, which is `2` as well.
> fix default severity level of an alert

- thehive4py/api.py
This PR fixes two cases of bad code indentation in exception handling code.
> fix two cases of bad indentation in exception handling code

- thehive4py/api.py
The get_case_tasks and create_case_task methods do not properly process the verify attribute which causes errors when testing locally with self-signed certificates. This commit adds *verify=self.cert* to both methods.
> Added verify parameter to calls

- samples/test-case-create__case-helper.py
- tests/test_case.py
- thehive4py/api.py
- thehive4py/exceptions.py
- thehive4py/models.py
I’ve added a helper class for interacting with cases as a higher level. It wraps the existing get_case and create_case methods and in both cases returns a Case instance rather than a requests Response instance. These methods have not been touched to backwards compatibility should not be affected.
There is a sample file included (test-case-create__case-helper.py) which can be compared with test-case-create.py to show how the usage changes.
The next step would be to wrap some of the other methods, e.g. to make it easier to work with case tasks, but I’ll wait for some feedback on this approach before going further.
It looks like there are some duplicated commits - I originally forked from master, and then realised I should have forked from develop, and when I tried to rebase against develop …
> Case helper

- samples/test-case-update.py
- thehive4py/api.py
Added a method to update a case. I thought this might have been better as a method on the Case class (e.g. case.update()) but the Case model class doesn't have a reference to the API client so it can't make that call. This is the simplest way I can see to add this functionality right now.
This addresses #5
> Added a method to update a case.

- thehive4py/models.py
The Case class's constructor did not add all attributes present in the JSON data returned from the API. For example, the `id` and `caseId`. You can now do:
```
case = thehive.case('some_case_id')
print(case.id)
print(case.caseId)  # The ID as shown in the web UI
print(case.status)
print(case.owner)
```
> Added missing attributes to the Case class.

- thehive4py/api.py
With the most recent version of TheHive4Py, trying to retrieve observables programmatically via the get_case_observables method was throwing the following error:
```
{u'message': u'JsResultException(errors:List((,List(JsonValidationError(List(Invalid query: unexpected [{"_parent":{"_type":"case","_query":{"_id":"AWA9SlYM_XlqkMKDzIB0"}}},{"_value":"Ok","_field":"status"}]),WrappedArray())))))', u'type': u'play.api.libs.json.JsResultException'}
```
I updated the code using the same structure present in the get_case_tasks method.
> fix get_case_observables method

- thehive4py/api.py
Fixed invalid reference to `CaseObservableException` in api.py.
> fix spelling of exception

- thehive4py/api.py
This commit adds the `update_alert` method to update an alert. The signature of the method is based on the `update_case` method.
> add update_alert to allow updating an alert

- thehive4py/query.py
The _field parameter was missing in the between function and was blocking request who used it as the hive say the query is not good
> Missing parameter _field in Between function

- thehive4py/api.py
The following PR adds an `update_case_tasks` method so that a given Task can be updated programmatically. This is related to Issue #6.
> Add Support for update_case_tasks method

- thehive4py/api.py
This pull requests adds the following functions:
* **get_case_task(taskId)** retrieve a single task by its id
* **get_task_log(attributes)** retrieve a single task log by its id
* **delete_case(case_id, force=False)** soft/hard delete a case
* **health()** retrieve health info
> Implement some more functions

- thehive4py/models.py
The Hive API supports creation of cases with custom owner/asignee. This is very useful if the case is beeing created by a bot, but the case must be opened by someone else.
> Added support for custom owner on Case creation

- thehive4py/models.py
Added IDs in all models
Fixes #120
> Added IDs in all models

- thehive4py/api.py
As a workaround for this issues
https://github.com/TheHive-Project/TheHive4py/issues/114
https://github.com/TheHive-Project/TheHive/issues/929
You can firstly get the alert `caseTemplate` before promoting it.
> Specify an optional case template parameter to promote_alert_to_case

- thehive4py/models.py
Add one line to extract case template ID from json response.
ID is needed to further actions with case templates like update or delete.
> Add id for case template

- thehive4py/auth.py
Importing requests module to fix the error :
```
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/thehive4py/auth.py", line 24, in __call__
req.headers['Authorization'] = requests.auth._basic_auth_str(self.username, self.password)
NameError: name 'requests' is not defined
```
> Importing requests module

- thehive4py/api.py
Fix for error identified by user CanTopay in issue #173. I corrected the  typo 'custom_field.madatory' to 'custom_field.mandatory'.
> Issue #173: corrected typo 'custom_field.madatory' to 'custom_field.mandatory'

- thehive4py/api.py
PR related to #195 
An alert's artifacts cannot be updated using the `update_alert` method because artifact serialization is skipped due to the incorrect usage of `hasattr` on the `data` patch dictionary.
Using the `in` operator instead to look up the key in the dictionary and trigger the artifact serialization if needed.
> Use dict key lookup instead of hasattr

- thehive4py/api.py
This PR adds an API function to merge an alert into an existing case.
NB! Adding empty JSON payload, since the backend API wants a POST request, but does not have any parameters defined as payload data.
> Merge alert to case

- thehive4py/api.py
and allow for params and query (#160)
> Make get_task_logs() use 'api/case/task/log/_search/' 

- thehive4py/api.py
Fixes: TheHive-Project/TheHive4py#165
1. This PR changes the `api.find_first` function to return a `requests.Response` object instead of a Python dict as it should be according to the docstrings.
2. Additionally, the previous behaviour was to still query for either all cases matching the query or a user specified range and then return only the first element from the `requests.Response` object.
This PR changes the logic by overwriting the `range` parameter to `0-1` which means we actually ask The Hive to only provide one case.
3. Removed the `range` parameter from the docstrings Arguments list, since we now set it statically.
> Fix documentation mismatch on api.find_first TheHive-Project/TheHive4py#165

- thehive4py/api.py
Delete an alert from TheHive.
NB! Added force parameter statically, since otherwise the deletion would not happen and I couldn't see any other changes happening if it was set to `0`.
> Add method to delete alert

- thehive4py/query.py
Fixed typo in the explanation of some functions: customField should be customFields.
> Fixed typo in explanation part of some functions in query.py

- thehive4py/api.py
Linters can be a good thing.
Fix exception handling error introduced in https://github.com/TheHive-Project/TheHive4py/pull/164
> Fix exception handling for merge_alert_into_case

- thehive4py/api.py
- thehive4py/exceptions.py
Added a boolean flag to get similar cases within the alert.
Previous API request was:
/api/alert/ffd8a6ff0cc6a65a34afc86306f297d0
With get_similar_case = True is:
/api/alert/ffd8a6ff0cc6a65a34afc86306f297d0?similarity=1
The PR is backward compatible (get_similar_case = False by default).
> Get alert with similarities

- tests/test_files.py
- thehive4py/models.py
Fix #35 for case observables (but not for other places where files can be added, such as alert artifacts).
This is mostly like the code posted in [this comment](https://github.com/TheHive-Project/TheHive4py/issues/35#issuecomment-462122212). It also has a test which fails without the code and passes with it.
> Pass in file-like objects for case observables

- thehive4py/api.py
I add a method to get the job information after executing the `run_analyzer` method
> add get_job_status method

- .gitignore
- README.md
- tests/test_alert_endpoint.py
- tests/utils.py
- thehive4py/endpoints/_base.py
- thehive4py/endpoints/alert.py
- thehive4py/types/alert.py
- thehive4py/types/case.py
- thehive4py/types/observable.py
- thehive4py/types/procedure.py
Main change is the ability to add observables in the alert creation.
In that case, the request needs to use a multipart
> Update for 5.0.1

- tests/test_case_endpoint.py
- thehive4py/endpoints/case.py
add set_share to case endpoint
> added case.set_share

- thehive4py/api.py
A fix for the issue #243 - nparent is specified as an int to get TheHive to return parent objects. Added into the "params" structure in "__find_rows" as an optional value. Will default to 0, to maintain current behavior if not specified.
> Fix for Issue 243 - allows parent objects to be returned

- thehive4py/errors.py
- thehive4py/session.py
This one is a convenience feature to better handle exceptions due to API errors.
At the moment one only has access to the parsed error message of an exception, e.g.:
```python
try:
...
except TheHiveError as err:
if "CreateError" in str(err):
print("handle create errors here")
else:
print("do generic error handling here")
```
From the above it is clear that the handling capabilities are limited to the parsed error string, while with this change one can do:
```python
try:
...
except TheHiveError as err:
if "CreateError" in err.message:
print("handle create errors here")
else:
if err.response:
if err.response.status_code == 401:
print("handle authentication error here")
else:
error_json = err.response.json()
```
> Persist error response data in TheHiveError

- .github/workflows/ci.yml
- setup.py
- thehive4py/client.py
- thehive4py/helpers.py
- thehive4py/query/filters.py
- thehive4py/query/sort.py
Experimenting with github actions/workflows
> Add basic ci workflow

- .github/workflows/ci.yml
- tests/conftest.py
- tests/test_custom_field_endpoint.py
- tests/test_observable_endpoint.py
- tests/test_observable_type_endpoint.py
- tests/utils.py
- thehive4py/client.py
- thehive4py/endpoints/observable_type.py
- thehive4py/types/observable_type.py
- Added an endpoint for observable types, the script contains four functions : create, get, delete and find. It passed the tests.
> Add observableType endpoints

- tests/test_alert_endpoint.py
- thehive4py/endpoints/alert.py
- thehive4py/types/alert.py
Complete the API for function `alert.promote_to_case`
> Add parameters to method alert.promote_to_case()

- thehive4py/endpoints/observable.py
Add a method to download an attachment from the observableendpoint class and be able to retrieve a file from an observable's id. The download can also be done with a zip and the parameter as_zip.
> Download an attachment from an observable

- pyproject.toml
Recently in other projects that are using `thehive4py` v2.x I started to receive errors from `mypy` like `error: Skipping analyzing 'thehive4py.xxx': found module but no type hints or library stubs`
Weird that it didn't show up before in CI checks.
Anyways it is an easy fix as according to PEP-561 a placeholder file called `py.typed` in the project root should fix the issue, and then `mypy` would respect the typehints of the library.
> add py.typed to the project to please mypy and make the library PEP-561 compliant

- tests/conftest.py
- thehive4py/types/task.py
Upgrade testing to v5.2.10.
Review task type hints.
> 317 review type hints for inputoutput objects

- .github/workflows/_build-package.yml
- .github/workflows/_integration-tests.yml
- .github/workflows/_static-checks.yml
- .github/workflows/_upload-package.yml
- tests/conftest.py
- tests/test_alert_endpoint.py
- thehive4py/endpoints/alert.py
Add attachment operations to the alert endpoint
> 319 attachement to an alert

- .github/workflows/_build-package.yml
- .github/workflows/_integration-tests.yml
- .github/workflows/_static-checks.yml
- .github/workflows/_upload-package.yml
- .github/workflows/main-cicd.yml
- README.md
- pyproject.toml
- tests/conftest.py
- tests/test_case_endpoint.py
- tests/test_custom_field_endpoint.py
- tests/test_user_endpoint.py
- tests/utils.py
> Rework test container

- pyproject.toml
The license in the Git repo for TheHive4py moved from AGPLv3+ to MIT, but the toml code did not get updated, this catches up the rest of the build environment and should allow for proper license use
At this moment, we cannot create a form of Docker Container because the build process does not support the use of the AGPLv3+ license and we were wondering why as the current version of TheHive4py is MIT licensed
These changes should allow a new release to be used in our and other license verified build processes
> Align pyproject.toml to Git Repo License of MIT

- pyproject.toml
- thehive4py/client.py
- thehive4py/session.py
> #340 - Add retry mechanism

- CHANGELOG.md
- setup.py
- thehive4py/__init__.py
> #352 - Add deprecation wraning to the 1.x codebase

- thehive4py/types/alert.py
- thehive4py/types/case.py
> #380 - Update case and alert types

- tests/test_query_filters.py
- thehive4py/query/__init__.py
- thehive4py/query/filters.py
This PR fixes the deprecation warnings of the comparison operators.
Unsure as if with `Contains` we should also update the dict field, not just emit a warning.
> Fix deprecations, add warning for Contains

- tests/test_init.py
- thehive4py/__init__.py
> #361 - Add deprecation warning for python 3.8

- tests/conftest.py
- tests/test_case_endpoint.py
- thehive4py/endpoints/case.py
- thehive4py/types/case.py
> #390 - Extend CaseEndpoint with apply_case_template method

- tests/test_cortex_endpoint.py
- thehive4py/types/cortex.py
As per https://github.com/TheHive-Project/TheHive4py/issues/395, this PR swaps the observableId field with the articfactId field and adds a regression test.
> Fix InputAnalyzerJob type and add regression test

- tests/test_case_endpoint.py
- thehive4py/endpoints/case.py
> #398 - Remove `update_share` method from case endpoint

- tests/conftest.py
> #408 - Use TheHive 5.4.8 in integration tests

- thehive4py/types/observable.py
Update OutputObservableRequired type with the tlpLabel and papLabel as both attributes are stated as required here https://docs.strangebee.com/thehive/api-docs/#tag/Observable/operation/Get%20Observable.
> #428 - Update OutputObservableRequired type

- docs/release-notes.md
- pyproject.toml
> #475 - Release 2.0.0b13
