TheHive-Project/TheHive4py

thehive4py/api.py
Added wrapper for find_cases that returns first case of result set based on query.
=> Find first

setup.py, thehive4py/api.py
New submission based on #34 which works with version 1.3.1.
=> Added get_task_logs method

thehive4py/api.py
=> Added the functionality to run a Cortex analyzer on an observable

thehive4py/models.py
This PR adds Sighted support for the Observable model.
=> Add Sighted Support to the Observable Model

thehive4py/api.py
Added a method for retrieving the linked cases given a case_id.
=> created get_linked_cases method in api

thehive4py/api.py
up until now there was no method available for searching and filtering of tasks.
=> added search support for tasks

thehive4py/models.py
Add support for task group names
=> support for task group names

samples/bulk-alert-merge-to-case.py
A sample script to mass merge alerts into a single case
=> Create new sample bulk-alert-merge-to-case.py

thehive4py/api.py
Added update_case_observable
Fix #121
=> Added update_case_observable

thehive4py/models.py
=> Support for json datetime

.gitignore, thehive4py/api.py, thehive4py/exceptions.py, thehive4py/models.py
Added API endpoints and corresponding models to create custom fields and case templates through TheHive API
=> Add support for case delete, creating custom fields and create case templates

thehive4py/api.py, thehive4py/exceptions.py
Add find_observables function.
Fix https://github.com/TheHive-Project/TheHive4py/issues/157
=> Add find_observables

thehive4py/api.py
=> Implement case task deletion via patch request

thehive4py/api.py
Added the function "MISP_export" to the file "api.py" that allows to export IOCs on a MISP instance.
=> Added MISP export functionality

thehive4py/models.py
It's just that easy! 
Fixes: https://github.com/TheHive-Project/TheHive4py/issues/169
=> Adding externalLink to Alert model

thehive4py/api.py
=> Get case observable function

docs/samples/case-operations.md
Added the update a case example.
=> Update a case - Example

tests/test_alert_endpoint.py, tests/test_case_endpoint.py, thehive4py/endpoints/alert.py, thehive4py/endpoints/case.py
=> #250 - Implement list comment methods for alerts and cases

setup.py, thehive4py/session.py
=> Use json.loads instead of relying on requests' json method

tests/test_alert_endpoint.py, tests/test_case_endpoint.py, thehive4py/endpoints/alert.py, thehive4py/endpoints/case.py, thehive4py/endpoints/procedure.py, thehive4py/types/procedure.py
Tests to be added, but before I want to make sure all the newly added methods are required by the issue.
=> 268 add case and alert ttps operations

tests/test_observable_endpoint.py, tests/utils.py, thehive4py/endpoints/_base.py, thehive4py/endpoints/observable.py
=> Test observable attachment download

tests/conftest.py, tests/test_case_endpoint.py, thehive4py/endpoints/case.py, thehive4py/types/page.py
Added page manipulation methods and corresponding tests to the case endpoint
=> #273 - Add page manipulation methods to case endpoint

thehive4py/types/alert.py, thehive4py/types/procedure.py
=> 277 - Fix InputAlert and InputProcedure type defs

.github/workflows/_integration-tests.yml, .github/workflows/main-cicd.yml, README.md, tests/conftest.py
=> #339 - add codecov action

.github/workflows/_build-docs.yml, .github/workflows/_build-package.yml, .github/workflows/_deploy-docs.yml, .github/workflows/_integration-tests.yml, .github/workflows/_static-checks.yml, .github/workflows/_upload-package.yml, .github/workflows/main-cicd.yml, pyproject.toml
=> #347 - Add support for Python 3.13

README.md
Convert thehive4py title into a h1 element
=> #301 - Adjust thehive4py title's font size

.github/workflows/_build-package.yml, .github/workflows/_upload-package.yml
As per https://github.com/actions/toolkit/blob/main/packages/artifact/docs/faq.md#which-versions-of-the-artifacts-packages-are-compatible
=> #367 - Align upload and download artifact versions

.github/release.yml
=> #362 - Add release.yml

tests/conftest.py
=> #381 - Use TheHive 5.4.6 in integration tests

thehive4py/session.py
=> #388 - Enhance session's error parse method

docs/examples/case.md, docs/reference.md, examples/case/advanced.py, examples/case/delete.py, examples/case/fetch_with_find.py, examples/case/fetch_with_get.py, examples/case/merge.py, examples/case/minimalistic.py, examples/case/obervable_simple.py, examples/case/observable_file.py, examples/case/pages_after_creation.py, examples/case/pages_during_creation.py, examples/case/procedures_after_creation.py, examples/case/tasks_after_creation.py, examples/case/tasks_during_creation.py, examples/case/update_bulk.py, examples/case/update_single.py, mkdocs.yml
=> #354 - Add case endpoint docs

thehive4py/endpoints/case.py
=> #354 - Add case endpoint docstrings

.github/workflows/_check-release-notes.yml, .github/workflows/main-cicd.yml, docs/release-notes.md, mkdocs.yml, scripts/linkify_release_notes.py
=> #355 - Add changelog to docs

docs/release-notes.md, pyproject.toml
=> #403 - Release v2.0.0b9

tests/conftest.py
=> #414 - Use TheHive v5.4.9 in integration tests

docs/examples/alert.md, examples/alert/fetch_with_find.py, examples/alert/observable_from_file.py, thehive4py/endpoints/alert.py
Fix examples and review alert docs wording.
=> #410 - Review and fix alert docs

docs/release-notes.md, scripts/linkify_release_notes.py
=> #411 - Fix changelog linkification script

tests/test_alert_endpoint.py, thehive4py/session.py
=> #417 - consider empty dicts in json requests

tests/conftest.py
=> #419 - Use TheHive v5.5.1 in integration tests

scripts/linkify_release_notes.py
Remove leftover quickfix functions from linkification script
=> #411 - Remove quickfix functions

docs/release-notes.md, pyproject.toml
=> #423 - Release v2.0.0b10

tests/test_organisation_endpoint.py, tests/utils.py, thehive4py/endpoints/organisation.py, thehive4py/types/organisation.py
Review the organisation endpoint's methods and types.
=> #302 - Review organisation endpoint methods and types

tests/test_alert_endpoint.py, thehive4py/endpoints/alert.py
=> #434 - Review alert endpoints

tests/test_case_endpoint.py, thehive4py/endpoints/case.py, thehive4py/types/case.py, thehive4py/types/custom_field.py
=> #435 - Review case endpoints

tests/test_task_log_endpoint.py, thehive4py/endpoints/task_log.py, thehive4py/types/task_log.py
=> #438 - Review task log endpoints

docs/release-notes.md, pyproject.toml
=> #452 - Release 2.0.0b11

thehive4py/endpoints/custom_field.py, thehive4py/types/custom_field.py
=> #441 - Review custom field endpoints

LICENSE, examples/alert/observable_from_file.py, examples/case/observable_file.py, noxfile.py, pyproject.toml, scripts/linkify_release_notes.py, tests/test_alert_endpoint.py, tests/test_case_endpoint.py, tests/test_observable_endpoint.py, tests/test_organisation_endpoint.py, tests/test_procedure_endpoint.py, tests/test_task_endpoint.py, tests/test_task_log_endpoint.py, tests/test_user_endpoint.py, thehive4py/errors.py
=> #473 - Introduce ruff to replace flake8 and black

tests/conftest.py
=> #477 - Use TheHive v5.5.5 in integration tests

noxfile.py
=> #480 - Fix deploy_docs dev script

README.md, docs/index.md, docs/release-notes.md, pyproject.toml
=> #485 - Release 2.0.0

thehive4py/types/alert.py, thehive4py/types/attachment.py, thehive4py/types/case.py, thehive4py/types/cortex.py, thehive4py/types/observable.py, thehive4py/types/organisation.py, thehive4py/types/page.py, thehive4py/types/share.py, thehive4py/types/task.py, thehive4py/types/task_log.py, thehive4py/types/user.py
=> #351 - Refactor required types using the NotRequired type hint

tests/test_case_endpoint.py, thehive4py/types/case.py
=> #495 - Fix incorrectly typed properties of InputUpdateCase

tests/conftest.py
=> #497 - Use TheHive v5.5.9 in integration tests

docs/examples/alert.md, docs/examples/case.md, examples/alert/observable_after_alerting.py, examples/case/obervable_simple.py, tests/test_alert_endpoint.py, tests/test_case_endpoint.py
=> #498 - Test and document bulk observable creation
